name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: bookreview
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done
      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bookreview
          SPRING_DATASOURCE_USERNAME: your_db_user
          SPRING_DATASOURCE_PASSWORD: your_db_password 